### ISSUE TITLE
SQL Windowing doesnt work on Hive 0.10

### ISSUE THREAD

**Issue by karthikbasa** [hbutani/SQLWindowing#29]
Hi,
I have followed the exact procedure and when i start the hive --service command it throws the below error
Exception in thread "main" java.lang.NoClassDefFoundError: JAR
Caused by: java.lang.ClassNotFoundException: JAR
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: JAR.  Program will exit.

I have used com.sap.hadoop.windowing-0.0.2-SNAPSHOT.jar and groovy-all-1.8.0.jar and my this is my sh

THISSERVICE=windowingCli
export SERVICE_LIST="${SERVICE_LIST}${THISSERVICE} "

windowingCli () {
  CLASS=com.sap.hadoop.windowing.WindowingHiveCliDriver
  if $cygwin; then
    HIVE_LIB=`cygpath -w "$HIVE_LIB"`
  fi
  JAR=${HIVE_LIB}/com.sap.hadoop.windowing-0.0.2-SNAPSHOT.jar
  exec $HADOOP jar $JAR $CLASS "$@"
}

windowingCli_help () {
  windowingCli "--help"
} 

please help me with this error. i am using cdh 4.7 which came with hive 0.10. thank you
